### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by ElliotFriend** [stlchristian/submergestl.com#20]
@hwomble suggested a countdown timer on the page. It should go above the "Learn More" button, and below the "SUBMERGE" title.

I love the idea, and I'm looking at a few ways to make this happen:
- [countdown.js](http://countdownjs.org/) looks pretty simple and straight-forward.
- [jQuery Countdown](http://keith-wood.name/countdown.html) seems equally straight-forward, and has some pre-built layouts we could use.
- [flip clock timer](http://www.gieson.com/Library/projects/utilities/countdown/) is a flip timer, like an old-school alarm clock. This is the style that I initially thought of, so I'm leaning toward this one.
- [jQuery.countdown](https://hilios.github.io/jQuery.countdown/) has the flip timer style that I like, though it seems a bit more confusing than 'flip clock timer'
- [FlipClock.js](http://flipclockjs.com/) has a pretty nicely polished version of the flip timer, based on jQuery -- _this one is actually working out quite nicely_

**Comment by ElliotFriend** [comment]
Here's another one:
- [jQuery.Countdown](https://hilios.github.io/jQuery.countdown/) has the flip timer style that I like

**Comment by hwomble** [comment]
SA-WEET!

**Comment by ElliotFriend** [comment]
@hwomble Should we include some kind of "begins in..." text? I'm thinking:

september 25-26, 2015
SUBMERGE
conference begins in:
206:03:07:45

Thoughts? I tried it out and I didn't like it a whooole lot, but wanted to get some feedback.

**Comment by hwomble** [comment]
What about "Countdown until ...." then put that ABOVE Submerge?? (Idea credit to Jeff Wright)

**Comment by ElliotFriend** [comment]
Here's the checklist from aed782a:
- [x] Center the countdown on the page
- [ ] Check for mobile compatibility
- [x] Style the labels better
- [x] Change colors of colons ':' ??
- [ ] Make sure that the time of the event is always shown as CDT

**Comment by ElliotFriend** [comment]
Figuring out what to do on a mobile device is going to be a bit harder for this. There's no reason that the JavaScript wouldn't work on a mobile device, but it's going to be tough to get the stuff to fit into the phone browser on one line. Perhaps for a little bit, we'll just hide the thing on a mobile phone until we can get it figured out.

**Comment by hwomble** [comment]
Yeah that sounds good to me
